const constants = {

    //teacher
    REGISTER_TEACHER: 'REGISTER_TEACHER',
    LOGIN_TEACHER: 'LOGIN_TEACHER',
    LOGOUT_TEACHER: 'LOGOUT_TEACHER',
    SET_TEACHER_ID: 'SET_TEACHER_ID',
    SET_TEACHER_DATA: 'SET_TEACHER_DATA',

    //terms
    SET_TERMS: 'SET_TERMS',
    EDIT_TERM: 'EDIT_TERM',
    CHOOSE_TERM: 'CHOOSE_TERM',

    //modals
    OPEN_REGISTER: 'OPEN_REGISTER',
    CLOSE_REGISTER: 'CLOSE_REGISTER',
    OPEN_LOGIN: 'OPEN_LOGIN',
    CLOSE_LOGIN: 'CLOSE_LOGIN'
}

export default constants